=== urra9598/sky-de-test-automation-framework/sky-tests-automation/test-scripts/schema_check/customer_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "customers",
  "type": "object",
  "required": [
    "customer_number",
    "account_sid",
    "source_system"
  ],
  "properties": {
    "customer_number": {"type": "string"},
    "account_sid": {"type": "string"},
    "source_system": {"type": "string"},
    "source_system_det": {"type": "string"},
    "css_des_customer_status": {"type": "string"},
    "birthdate": {"type": "string", "format": "date"},
    "salutation": {"type": "string"},
    "firstname": {"type": "string"},
    "lastname": {"type": "string"},
    "country": {"type": "string"},
    "postal_code": {"type": "string"},
    "city": {"type": "string"},
    "street": {"type": "string"},
    "add_des_house_number": {"type": "string"}
  }
}

=== urra9598/sky-de-test-automation-framework/sky-tests-automation/test-scripts/schema_check/expected-result/expected_records.json
[
  {
    "customer_number": "jujMirwARQ",
    "account_sid": "KdZUhgJSci",
    "source_system": "ybkUNeTnum",
    "source_system_det": "ZOPBLoQNjd",
    "css_des_customer_status": "DaJJMvHpMg",
    "birthdate": "VvMrdEJGqO",
    "salutation": "VQgGfbayAm",
    "firstname": "ESVUCkuZJf",
    "lastname": "pKQrdMcwwR",
    "country": "rYrxASQCzt",
    "postal_code": "iDdqdbmAjW",
    "city": "dFhUUiKWSn",
    "street": "kluErXhSpQ",
    "add_des_house_number": "QDsqJHpFTq"
  },
  {
    "customer_number": "fwbTNxdPEx",
    "account_sid": "RhhRVapotm",
    "source_system": "CVEKIyCHBn",
    "source_system_det": "RioQfZAtFz",
    "css_des_customer_status": "trUiCoCQlw",
    "birthdate": "NBSDypvZQS",
    "salutation": "EmssNWwuzf",
    "firstname": "uqsLuqRuDH",
    "lastname": "NBKafefrJJ",
    "country": "olEZiVihzt",
    "postal_code": "RzQNocHNUU",
    "city": "JgnAtCPdwO",
    "street": "uyPNbtZSXe",
    "add_des_house_number": "QytuLoTiVr"
  },
  {
    "customer_number": "STGfSjTepp",
    "account_sid": "VVAqOBdfcx",
    "source_system": "iAGzekujEh",
    "source_system_det": "kvwNLTdgOP",
    "css_des_customer_status": "gHPCKDnBje",
    "birthdate": "BVdwjZyuRr",
    "salutation": "MFvIcEUBzk",
    "firstname": "hAeZarNwLw",
    "lastname": "IHRpQHqaGv",
    "country": "TAmStMefZa",
    "postal_code": "YOubsTjCXD",
    "city": "IhkYmRevGt",
    "street": "gdnnqvcQLQ",
    "add_des_house_number": "fhBiHgqeWL"
  },
  {
    "customer_number": "UtgxFFKeoR",
    "account_sid": "aqcJwsMKOn",
    "source_system": "HGmlyCrchW",
    "source_system_det": "EUWjDeXNuj",
    "css_des_customer_status": "aLTSLGqonL",
    "birthdate": "XHgXuvXNNX",
    "salutation": "lFsZNoDnuj",
    "firstname": "EWUHIGQzMu",
    "lastname": "MAIQoRcbuB",
    "country": "ZsBtvsWsnx",
    "postal_code": "pLHempRlpp",
    "city": "NnScpqXubG",
    "street": "kECEpZyuRu",
    "add_des_house_number": "WUpPsOPcwD"
  },
  {
    "customer_number": "kCodYXBwaU",
    "account_sid": "LHknrRvjUH",
    "source_system": "xaheJkhQOv",
    "source_system_det": "pNVLvGWzYx",
    "css_des_customer_status": "cgbtyLVWak",
    "birthdate": "FaNGPpQyIk",
    "salutation": "UplbGkhHCF",
    "firstname": "bjCovypGTq",
    "lastname": "bDDBBBAbMy",
    "country": "ZLUnwvttJi",
    "postal_code": "spMqwUttac",
    "city": "pJcyUSKWsm",
    "street": "umvpctbrOj",
    "add_des_house_number": "UFCavvZqWl"
  }
]
